### ISSUE TITLE
Dynamic role mapping based on Chef environment

### ISSUE THREAD

**Issue by gites** [svagner/vault-auth-chef#10]
We are using the same role on `prod` and `dev` environment. The differences between `prod ` and `dev` are handled internally in role logic. The services running on `prod` and `dev` need to have access to different secrets paths. I would like to add a feature that would allow for mapping one role to different policies depending on with environment chef-client is running. After some internal team discussion we ended up with view ideas on how it should be implemented, but none of those is an obvious go-to solution.

The ideas we had:

- use some kind of variables in roles to policy definitions that will be mapped by the plugin to values know to Chef Server. Example:
```
vault read auth/chef/map/roles/dynamic-role
Key       Value
---       -----
key       dynamic-role
policy    dynamic-policy-%env%
```
where `%env%` would be mapped to value from Chef environment. A plus for this is that it could be used to map other values, like tags or platform. 

- extend role mapping to have `env` policy. Example:
```
vault read auth/chef/map/roles/dynamic-role
Key       Value
---       -----
key       dynamic-role
policy    dynamic-policy-prod
env       prod
policy    dynamic-policy-dev
env       dev
```
That looks pretty nice, but I'm unsure it is possible with Vault API.

- add one more level to role mappings. Example:
```
vault read auth/chef/map/roles/dynamic-role/prod
Key       Value
---       -----
key       dynamic-role
policy    dynamic-policy-prod

vault read auth/chef/map/roles/dynamic-role/dev
Key       Value
---       -----
key       dynamic-role
policy    dynamic-policy-dev
```

I'm wondering if you have any thoughts or preferences on that topic.

**Comment by svagner** [comment]
I very like first idea. But here can be some problems, because we should do something in method Policies for PolicyMap: https://github.com/svagner/vault-auth-chef/blob/master/src/vault-auth-chef/chefclient/path_auth.go#L163.

I think we can do it in more simple way with existing data;)
https://github.com/hashicorp/vault/blob/master/website/source/guides/identity/policy-templating.html.md https://github.com/svagner/vault-auth-chef/blob/master/src/vault-auth-chef/chefclient/path_auth.go#L63

**Comment by gites** [comment]
Thanks for suggesting policy templating but that thing is closely tied to the identity secrets backend. Basically, every host would need to have manually created the identity entry and assigned proper metadata (chef env). The identity backed uses its own metadata, not those returned with the token.

I will try to implement something based on the first idea. Let's see how it will go.

**Comment by gites** [comment]
Created a PR https://github.com/svagner/vault-auth-chef/pull/11 that implements this feature. I'm running this for a week now, and it seems to be pretty stable.
