### ISSUE TITLE
assigning polices based on run_list from node object is insecure

### ISSUE THREAD

**Issue by gites** [svagner/vault-auth-chef#6]
run_list in host node object can be overwritten by hosts itself. This can potentially lead to privilege escalation by allowing to assign additional roles to the run_list by the host itself, and thru that gaining access to additional secrets in Vault.

Also adding a new Chef role to a host, that require a new set of permissions in Vault will fail. On a first chef-client run the new role is not in the host node object run_list and can't be used in role-policy mapping. This leads to the chef-client failure as it can't read secrets from Vault needed by newly assigned role.

**Comment by universam1** [comment]
@sme

**Comment by svagner** [comment]
Hi @gites ! Thanks for your contribution! I'm not sure about possibility of overriding run_list on the chef server using host key. Unfortunately I don't have chef server installation now for check that. Could you please provide some details how it can be made from chef client side?

For second case it is possible to add auth by fqdn as instance.

**Comment by gites** [comment]
@svagner Steps to edit run list using host key:

1. Login to some server, go to `/etc/chef/`
2. Run: `export EDITOR=vim ; knife node edit $(hostname) -c client.rb ` add/delete roles and save your changes.
3. Run `knife node show $(hostname) -c client.rb` to verify that your changes were saved to Chef Server.

Before:
```
root@dev-wac-s1:/etc/chef# knife node show dev-wac-s1 -c client.rb
Node Name:   dev-wac-s1
Environment: dev
FQDN:        dev-wac-s1
IP:          10.8.38.22
Run List:    role[discovery-18], role[common-18]
```
After:
```
root@dev-wac-s1:/etc/chef# knife node show dev-wac-s1 -c client.rb
Node Name:   dev-wac-s1
Environment: dev
FQDN:        dev-wac-s1
IP:          10.8.38.22
Run List:    role[discovery-18], role[common-18], role[edit-edit-edit-18]
```

Some reading material:
https://coderanger.net/chef-and-vault/
https://github.com/chef/chef-rfc/blob/master/rfc045-node_state_separation.md
https://github.com/hashicorp/vault/pull/2226


As for second thing. That's a good point. But I'm more into service level abstraction that is given by the role to policy mapping feature. I don't care about one sever, but the whole bunch of them. Adding mapping by hostname will not scale in my use case.

**Comment by svagner** [comment]
Yes, I understand you explanation, thanks! Generally I see that it is basically lack of permissions settings on chef server side. If you can change run_list you can basically receive some sensitive information anyway. But I see your point and your use case. What I offer to do:
- make data_bag source as optional - let's give choose for users. Also if would be great to provide some documentation for using data_bags as source for auth with explanation use case
- let's try to change run list using client key (we can try to change run_list to the same value). If run_list was changes successfully - print security warning to vault logs.
- add mapping based on hostgroups (hostgroup-acl policy)

If you agree with my point of view and it will cover your use case as well (using data_bags, but it is just based on your settings. Users can use another flow with auth based on run_list/fqdn/groups) - we can start to work on implementation of those features. What do you think about it?

**Comment by gites** [comment]
We can go with making `data_bags` source as an option. (Actually that was my idea at first, but it felt kinda wrong to leave an option that could be used to privileges escalation. The overwriting run_list in a node should be handled somehow.) 
I will make a follow-up PR in the next week.

**Comment by svagner** [comment]
Thanks @gites ! I think I will add some extra checks with logging to vault about it. I think it should really be solved be restriction on chef side. I also think too add mapping based on node groups.

**Comment by gites** [comment]
@svagner I changed my pr and now data bags can be chosen optionally as a source of the run_list.
